
#Todas las configuraciones relacionadas con el núcleo del juego
[gameplay]
	#Si generar o no suministros en los cofres de campamentos y barcos de suministro. [Defecto: true]
	generatesupplyloot = true

#Todas las configuraciones relacionadas con peticiones del sistema
[requestsystem]
	#¿Debería el sistema de peticiones mostrar información de depuración? Útil si no está funcionando bien. [Defecto: false]
	enabledebuglogging = false

