[server.pv.addon.broadcast]
broadcasting_specific = "משדר ל-%s"
broadcasting_wide = "משדר ל %s-רחב"

[server.pv.addon.broadcast.command]
world_set = "הגדר שידור עם מצב World ל-%s"
world_usage = "שימוש: <vbroadcast world <world names/"
usage = "שימוש: <vbroadcast <range|server|world> <range|world names/"
range_set = "הגדר שידור עם מרחק %d"
server_set = "הגדר שידור עם מצב Server"
range_usage = "שימוש: <vbroadcast range <number greater than 0/"
[client.pv.activation]
broadcast = "שידור"
